// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {php} from '../models';
import {config} from '../models';
import {main} from '../models';
import {logger} from '../models';
import {nodejs} from '../models';
import {sites} from '../models';
import {tray} from '../models';

export function ClearDebugLog():Promise<void>;

export function Context():Promise<context.Context>;

export function CreateServiceDatabase(arg1:string,arg2:string):Promise<void>;

export function CreateSite(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteSite(arg1:string):Promise<void>;

export function DisableDebug():Promise<void>;

export function DropServiceDatabase(arg1:string,arg2:string):Promise<void>;

export function EnableDebug():Promise<void>;

export function GetAllStatuses():Promise<Record<string, string>>;

export function GetAvailableNodeVersions():Promise<Array<string>>;

export function GetAvailablePhpVersions():Promise<Array<php.AvailablePhpVersion>>;

export function GetAvailableVersions(arg1:string):Promise<Array<string>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetDashboardStatus():Promise<main.DashboardStatus>;

export function GetDebugLogPath():Promise<string>;

export function GetInstalledVersions(arg1:string):Promise<Array<string>>;

export function GetLogFiles():Promise<Array<logger.LogFile>>;

export function GetNodeVersions():Promise<Array<nodejs.NodeVersion>>;

export function GetPgwebStatus():Promise<main.PgwebStatus>;

export function GetPhpVersions():Promise<Array<php.PhpVersion>>;

export function GetServiceLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function GetSites():Promise<Array<sites.Site>>;

export function GetTotalSiteCount():Promise<number>;

export function GetTraySites():Promise<Array<tray.SiteInfo>>;

export function GetWebAdminItems():Promise<Array<tray.WebAdminItem>>;

export function GetWebAdminURL(arg1:string):Promise<string>;

export function InitService(arg1:string):Promise<void>;

export function InstallPgweb():Promise<void>;

export function InstallShellIntegration():Promise<void>;

export function InstallVersion(arg1:string,arg2:string):Promise<void>;

export function InstallWebAdmin(arg1:string,arg2:string):Promise<void>;

export function IsCAInstalled():Promise<boolean>;

export function IsDebugEnabled():Promise<boolean>;

export function IsShellIntegrated():Promise<boolean>;

export function ListServiceDatabases(arg1:string):Promise<Array<main.DatabaseEntry>>;

export function OpenPgweb():Promise<void>;

export function OpenSiteInBrowser(arg1:string):Promise<void>;

export function OpenWebAdmin(arg1:string):Promise<void>;

export function OpenWebAdminInBrowser(arg1:string):Promise<void>;

export function ReadLog(arg1:string,arg2:number):Promise<Array<string>>;

export function RestartService(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetupCA():Promise<void>;

export function StartPgweb():Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopPgweb():Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function SwitchVersion(arg1:string,arg2:string):Promise<void>;

export function UninstallShellIntegration():Promise<void>;

export function UninstallVersion(arg1:string,arg2:string):Promise<void>;

export function UninstallWebAdmin(arg1:string):Promise<void>;
