// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDebugLog() {
  return window['go']['main']['App']['ClearDebugLog']();
}

export function CreateServiceDatabase(arg1, arg2) {
  return window['go']['main']['App']['CreateServiceDatabase'](arg1, arg2);
}

export function CreateSite(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSite'](arg1, arg2, arg3);
}

export function DeleteSite(arg1) {
  return window['go']['main']['App']['DeleteSite'](arg1);
}

export function DisableDebug() {
  return window['go']['main']['App']['DisableDebug']();
}

export function DropServiceDatabase(arg1, arg2) {
  return window['go']['main']['App']['DropServiceDatabase'](arg1, arg2);
}

export function EnableDebug() {
  return window['go']['main']['App']['EnableDebug']();
}

export function GetAllStatuses() {
  return window['go']['main']['App']['GetAllStatuses']();
}

export function GetAvailableNodeVersions() {
  return window['go']['main']['App']['GetAvailableNodeVersions']();
}

export function GetAvailablePhpVersions() {
  return window['go']['main']['App']['GetAvailablePhpVersions']();
}

export function GetAvailableVersions(arg1) {
  return window['go']['main']['App']['GetAvailableVersions'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDashboardStatus() {
  return window['go']['main']['App']['GetDashboardStatus']();
}

export function GetDebugLogPath() {
  return window['go']['main']['App']['GetDebugLogPath']();
}

export function GetInstalledVersions(arg1) {
  return window['go']['main']['App']['GetInstalledVersions'](arg1);
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetNodeVersions() {
  return window['go']['main']['App']['GetNodeVersions']();
}

export function GetPgwebStatus() {
  return window['go']['main']['App']['GetPgwebStatus']();
}

export function GetPhpVersions() {
  return window['go']['main']['App']['GetPhpVersions']();
}

export function GetServiceLogs(arg1, arg2) {
  return window['go']['main']['App']['GetServiceLogs'](arg1, arg2);
}

export function GetSites() {
  return window['go']['main']['App']['GetSites']();
}

export function GetWebAdminURL(arg1) {
  return window['go']['main']['App']['GetWebAdminURL'](arg1);
}

export function InitService(arg1) {
  return window['go']['main']['App']['InitService'](arg1);
}

export function InstallPgweb() {
  return window['go']['main']['App']['InstallPgweb']();
}

export function InstallShellIntegration() {
  return window['go']['main']['App']['InstallShellIntegration']();
}

export function InstallVersion(arg1, arg2) {
  return window['go']['main']['App']['InstallVersion'](arg1, arg2);
}

export function InstallWebAdmin(arg1, arg2) {
  return window['go']['main']['App']['InstallWebAdmin'](arg1, arg2);
}

export function IsCAInstalled() {
  return window['go']['main']['App']['IsCAInstalled']();
}

export function IsDebugEnabled() {
  return window['go']['main']['App']['IsDebugEnabled']();
}

export function IsShellIntegrated() {
  return window['go']['main']['App']['IsShellIntegrated']();
}

export function ListServiceDatabases(arg1) {
  return window['go']['main']['App']['ListServiceDatabases'](arg1);
}

export function OpenPgweb() {
  return window['go']['main']['App']['OpenPgweb']();
}

export function OpenWebAdmin(arg1) {
  return window['go']['main']['App']['OpenWebAdmin'](arg1);
}

export function ReadLog(arg1, arg2) {
  return window['go']['main']['App']['ReadLog'](arg1, arg2);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetupCA() {
  return window['go']['main']['App']['SetupCA']();
}

export function StartPgweb() {
  return window['go']['main']['App']['StartPgweb']();
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopPgweb() {
  return window['go']['main']['App']['StopPgweb']();
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function SwitchVersion(arg1, arg2) {
  return window['go']['main']['App']['SwitchVersion'](arg1, arg2);
}

export function UninstallShellIntegration() {
  return window['go']['main']['App']['UninstallShellIntegration']();
}

export function UninstallVersion(arg1, arg2) {
  return window['go']['main']['App']['UninstallVersion'](arg1, arg2);
}

export function UninstallWebAdmin(arg1) {
  return window['go']['main']['App']['UninstallWebAdmin'](arg1);
}
