// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDebugLog() {
  return window['go']['main']['App']['ClearDebugLog']();
}

export function DisableDebug() {
  return window['go']['main']['App']['DisableDebug']();
}

export function EnableDebug() {
  return window['go']['main']['App']['EnableDebug']();
}

export function GetAvailableNodeVersions() {
  return window['go']['main']['App']['GetAvailableNodeVersions']();
}

export function GetAvailablePhpVersions() {
  return window['go']['main']['App']['GetAvailablePhpVersions']();
}

export function GetDashboardStatus() {
  return window['go']['main']['App']['GetDashboardStatus']();
}

export function GetDebugLogPath() {
  return window['go']['main']['App']['GetDebugLogPath']();
}

export function GetDnsStatus() {
  return window['go']['main']['App']['GetDnsStatus']();
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetNginxStatus() {
  return window['go']['main']['App']['GetNginxStatus']();
}

export function GetNodeVersions() {
  return window['go']['main']['App']['GetNodeVersions']();
}

export function GetPhpFpmStatus() {
  return window['go']['main']['App']['GetPhpFpmStatus']();
}

export function GetPhpVersions() {
  return window['go']['main']['App']['GetPhpVersions']();
}

export function GetSites() {
  return window['go']['main']['App']['GetSites']();
}

export function InstallNode(arg1) {
  return window['go']['main']['App']['InstallNode'](arg1);
}

export function InstallPhp(arg1) {
  return window['go']['main']['App']['InstallPhp'](arg1);
}

export function InstallShellIntegration() {
  return window['go']['main']['App']['InstallShellIntegration']();
}

export function IsCAInstalled() {
  return window['go']['main']['App']['IsCAInstalled']();
}

export function IsDebugEnabled() {
  return window['go']['main']['App']['IsDebugEnabled']();
}

export function IsShellIntegrated() {
  return window['go']['main']['App']['IsShellIntegrated']();
}

export function LinkSite(arg1, arg2) {
  return window['go']['main']['App']['LinkSite'](arg1, arg2);
}

export function ReadLog(arg1, arg2) {
  return window['go']['main']['App']['ReadLog'](arg1, arg2);
}

export function ReloadNginx() {
  return window['go']['main']['App']['ReloadNginx']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetActiveNode(arg1) {
  return window['go']['main']['App']['SetActiveNode'](arg1);
}

export function SetActivePhp(arg1) {
  return window['go']['main']['App']['SetActivePhp'](arg1);
}

export function SetupCA() {
  return window['go']['main']['App']['SetupCA']();
}

export function StartDns() {
  return window['go']['main']['App']['StartDns']();
}

export function StartNginx() {
  return window['go']['main']['App']['StartNginx']();
}

export function StartPhpFpm() {
  return window['go']['main']['App']['StartPhpFpm']();
}

export function StopDns() {
  return window['go']['main']['App']['StopDns']();
}

export function StopNginx() {
  return window['go']['main']['App']['StopNginx']();
}

export function StopPhpFpm() {
  return window['go']['main']['App']['StopPhpFpm']();
}

export function UninstallNode(arg1) {
  return window['go']['main']['App']['UninstallNode'](arg1);
}

export function UninstallPhp(arg1) {
  return window['go']['main']['App']['UninstallPhp'](arg1);
}

export function UninstallShellIntegration() {
  return window['go']['main']['App']['UninstallShellIntegration']();
}

export function UnlinkSite(arg1) {
  return window['go']['main']['App']['UnlinkSite'](arg1);
}
