// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {php} from '../models';
import {main} from '../models';
import {dns} from '../models';
import {log} from '../models';
import {nginx} from '../models';
import {node} from '../models';
import {site} from '../models';

export function ClearDebugLog():Promise<void>;

export function DisableDebug():Promise<void>;

export function EnableDebug():Promise<void>;

export function GetAvailableNodeVersions():Promise<Array<string>>;

export function GetAvailablePhpVersions():Promise<Array<php.AvailablePhpVersion>>;

export function GetDashboardStatus():Promise<main.DashboardStatus>;

export function GetDebugLogPath():Promise<string>;

export function GetDnsStatus():Promise<dns.ServiceStatus>;

export function GetLogFiles():Promise<Array<log.LogFile>>;

export function GetNginxStatus():Promise<nginx.ServiceStatus>;

export function GetNodeVersions():Promise<Array<node.NodeVersion>>;

export function GetPhpFpmStatus():Promise<php.FpmStatus>;

export function GetPhpVersions():Promise<Array<php.PhpVersion>>;

export function GetSites():Promise<Array<site.Site>>;

export function InstallNode(arg1:string):Promise<void>;

export function InstallPhp(arg1:string):Promise<void>;

export function InstallShellIntegration():Promise<void>;

export function IsCAInstalled():Promise<boolean>;

export function IsDebugEnabled():Promise<boolean>;

export function IsShellIntegrated():Promise<boolean>;

export function LinkSite(arg1:string,arg2:string):Promise<void>;

export function ReadLog(arg1:string,arg2:number):Promise<Array<string>>;

export function ReloadNginx():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetActiveNode(arg1:string):Promise<void>;

export function SetActivePhp(arg1:string):Promise<void>;

export function SetupCA():Promise<void>;

export function StartDns():Promise<void>;

export function StartNginx():Promise<void>;

export function StartPhpFpm():Promise<void>;

export function StopDns():Promise<void>;

export function StopNginx():Promise<void>;

export function StopPhpFpm():Promise<void>;

export function UninstallNode(arg1:string):Promise<void>;

export function UninstallPhp(arg1:string):Promise<void>;

export function UninstallShellIntegration():Promise<void>;

export function UnlinkSite(arg1:string):Promise<void>;
